site_name: Physics Simulation
site_url: https://sjohnsonaz.github.io/physics-simulation
repo_url: https://github.com/sjohnsonaz/physics-simulation
copyright: Copyright &copy; 2017 Sean Johnson
pages:
    - Home: index.md
theme: readthedocs